### ISSUE TITLE
Issues With Dynamic Hierarchical Form Template

### ISSUE THREAD

**Issue by Prudhvi1109** [pegasystems/constellation-ui-gallery#64] opened 2024-06-20 09:41 UTC
Please find below issues for Dynamic Hierarchical Form Template.

1. Once we delete option in Check box combo, it is not getting populated again in the auto complete
2. Property message is not displaying on the property.

Step to reproduce for Issue 1:

1. We have imported ConstellationUIGallery:01-01 for using Dynamic Hierarchical Form Template
2. Created a view using Dynamic Hierarchical Form Template
3. Configured all details 
4. Once we delete option in Check box combo, it is not getting populated again in the auto complete

Step to reproduce for Issue 2:
1. Setting error message on some property in the tab, message is not getting populated on the proper

[Dynamic Hierarchical Form Template Issue.docx](https://github.com/user-attachments/files/15911897/Dynamic.Hierarchical.Form.Template.Issue.docx)

**Comment by ricmars** [comment] 2024-06-20 13:14
several questions
1 - Did you try with the demo application provided on Github and the example shipped in this application
2 - Are you running on 23.1?
3 - Why do you have the same field 'role' exposed twice on the screenshot - the selection field should only present once on the UI otherwise it will conflict and map to the same property in the client store
4 - Is there any network error or javascript error in the console on delete?
5- If you expand the dropdown of role, do you see all the available options? do you see the list of roles coming back correctly from the dx api response (see screenshot)
![Screenshot 2024-06-20 at 9 12 30 AM](https://github.com/pegasystems/constellation-ui-gallery/assets/29442140/544ffa66-7cad-4340-b9be-a41fec1baf42)

For issue #2 - this is currently a known limitation - the UI is not rendered when there is a validation error to show the field validation error - I will try to enhance this component to add support for this functionality

**Comment by Prudhvi1109** [comment] 2024-06-24 04:16
Hi,

With z-index 6999 it is not showing up, now we  have updated that to 7000 then it is showing. Please find attached screen shot for reference.
![image](https://github.com/pegasystems/constellation-ui-gallery/assets/173355175/75f7c259-8dc1-49f9-9cc5-de9a16bd80c3)
![image](https://github.com/pegasystems/constellation-ui-gallery/assets/173355175/647ce5f9-6220-45c9-aa16-c9f6d7b678d6)

**Comment by ricmars** [comment] 2024-06-25 23:18
I cannot reproduce this issue on 23.1 with a regular work portal , a z-index of 1 should work fine too - are you using web-embed? 

for issue #2 - this is a known limitation and will see if the implementation can be enhanced

**Comment by Prudhvi1109** [comment] 2024-06-26 07:12
Hi, We are using it in Create View Modal of a case Type.

**Comment by Prudhvi1109** [comment] 2024-07-02 10:52
Hi, 
There is another issue with Dynamic Hierarchical Form Template, where even if we make selection field as required always, component is not showing asterisk symbol besides to that field. Please find below screen shots for reference.

![image](https://github.com/pegasystems/constellation-ui-gallery/assets/173355175/01a41e21-6eef-46c9-904a-23c5fa1efea6)
![image](https://github.com/pegasystems/constellation-ui-gallery/assets/173355175/3fd7a1ab-e411-469b-b2a4-5aad20bd1bc0)

**Comment by ricmars** [comment] 2024-07-02 21:25
https://github.com/pegasystems/constellation-ui-gallery/pull/65 will fix 2 of the reported issues (required missing on the product combobox + issue with combobox z-index in create modal)
 
To fully validate that the products are required and you need at least one product, you need a validate activity on the post-processing of the flow action to validate that at least one product is selected

The other request which is to perform field validation on the embedded tab content - this is not possible in 23.1 - There might be a way to achieve this in 24.1, but this will require extra effort. 

closing this issue since all issues have been answered-  please open a new issue for reporting other issues - Also this project is an open source project and if you find bugs or issues, you are welcome to contribute this project and provide the fix.

**Closed by ricmars** 2024-07-02 21:25 UTC
